const states = [
    { id: 1, code: 'AL', description: 'ALABAMA' },
    { id: 2, code: 'AK', description: 'ALASKA' },
    { id: 3, code: 'AS', description: 'AMERICAN SAMOA' },
    { id: 4, code: 'AZ', description: 'ARIZONA' },
    { id: 5, code: 'AR', description: 'ARKANSAS' },
    { id: 6, code: 'CA', description: 'CALIFORNIA' },
    { id: 7, code: 'CO', description: 'COLORADO' },
    { id: 8, code: 'CT', description: 'CONNECTICUT' },
    { id: 9, code: 'DE', description: 'DELAWARE' },
    { id: 10, code: 'DC', description: 'DISTRICT OF COLUMBIA' },
    { id: 11, code: 'FM', description: 'FEDERATED STATES OF MICRONESIA' },
    { id: 12, code: 'FL', description: 'FLORIDA' },
    { id: 13, code: 'GA', description: 'GEORGIA' },
    { id: 14, code: 'GU', description: 'GUAM' },
    { id: 15, code: 'HI', description: 'HAWAII' },
    { id: 16, code: 'ID', description: 'IDAHO' },
    { id: 17, code: 'IL', description: 'ILLINOIS' },
    { id: 18, code: 'IN', description: 'INDIANA' },
    { id: 19, code: 'IA', description: 'IOWA' },
    { id: 20, code: 'KS', description: 'KANSAS' },
    { id: 21, code: 'KY', description: 'KENTUCKY' },
    { id: 22, code: 'LA', description: 'LOUISIANA' },
    { id: 23, code: 'ME', description: 'MAINE' },
    { id: 24, code: 'MH', description: 'MARSHALL ISLANDS' },
    { id: 25, code: 'MD', description: 'MARYLAND' },
    { id: 26, code: 'MA', description: 'MASSACHUSETTS' },
    { id: 27, code: 'MI', description: 'MICHIGAN' },
    { id: 28, code: 'MN', description: 'MINNESOTA' },
    { id: 29, code: 'MS', description: 'MISSISSIPPI' },
    { id: 30, code: 'MO', description: 'MISSOURI' },
    { id: 31, code: 'MT', description: 'MONTANA' },
    { id: 32, code: 'NE', description: 'NEBRASKA' },
    { id: 33, code: 'NV', description: 'NEVADA' },
    { id: 34, code: 'NH', description: 'NEW HAMPSHIRE' },
    { id: 35, code: 'NJ', description: 'NEW JERSEY' },
    { id: 36, code: 'NM', description: 'NEW MEXICO' },
    { id: 37, code: 'NY', description: 'NEW YORK' },
    { id: 38, code: 'NC', description: 'NORTH CAROLINA' },
    { id: 39, code: 'ND', description: 'NORTH DAKOTA' },
    { id: 40, code: 'MP', description: 'NORTHERN MARIANA ISLANDS' },
    { id: 41, code: 'OH', description: 'OHIO' },
    { id: 42, code: 'OK', description: 'OKLAHOMA' },
    { id: 43, code: 'OR', description: 'OREGON' },
    { id: 44, code: 'PW', description: 'PALAU' },
    { id: 45, code: 'PA', description: 'PENNSYLVANIA' },
    { id: 46, code: 'PR', description: 'PUERTO RICO' },
    { id: 47, code: 'RI', description: 'RHODE ISLAND' },
    { id: 48, code: 'SC', description: 'SOUTH CAROLINA' },
    { id: 49, code: 'SD', description: 'SOUTH DAKOTA' },
    { id: 50, code: 'TN', description: 'TENNESSEE' },
    { id: 51, code: 'TX', description: 'TEXAS' },
    { id: 52, code: 'UT', description: 'UTAH' },
    { id: 53, code: 'VT', description: 'VERMONT' },
    { id: 54, code: 'VI', description: 'VIRGIN ISLANDS' },
    { id: 55, code: 'VA', description: 'VIRGINIA' },
    { id: 56, code: 'WA', description: 'WASHINGTON' },
    { id: 57, code: 'WV', description: 'WEST VIRGINIA' },
    { id: 58, code: 'WI', description: 'WISCONSIN' },
    { id: 59, code: 'WY', description: 'WYOMING' },
    { id: 60, code: 'AA', description: 'ARMED FORCES AMERICAS' },
    { id: 61, code: 'AE', description: 'ARMED FORCES EUROPE' },
    { id: 62, code: 'AP', description: 'ARMED FORCES PACIFIC' },
];
export default states;
